import { View, Text, Pressable, StyleSheet } from "react-native";
import { P } from "../theme/proTheme";

export function Page({children}){ return <View style={s.page}>{children}</View>; }
export function Header({title,subtitle,right}){ return <View style={s.header}>{!!title&&<View><Text style={s.title}>{title}</Text>{!!subtitle&&<Text style={s.subtitle}>{subtitle}</Text>}</View>}{right}</View>; }
export function Card({children,style}){ return <View style={[s.card,style]}>{children}</View>; }
export function CTA({children,onPress,tone="blue"}){ const bg=tone==="buy"?P.color.green:tone==="sell"?P.color.red:tone==="ghost"?P.color.blueSoft:P.color.blue; return <Pressable onPress={onPress} style={({pressed})=>[s.cta,{backgroundColor:bg,borderColor:tone==="ghost"?P.color.blue:bg},pressed&&{opacity:.8}]}><Text style={[s.ctaText,tone==="ghost"&&{color:P.color.blue}]}>{children}</Text></Pressable>; }
export function Segments({tabs,active,onChange}){ return <View style={s.segments}>{tabs.map(t=><Pressable key={t} onPress={()=>onChange(t)} style={[s.segment,active===t&&s.segmentActive]}><Text style={[s.segmentText,active===t&&s.segmentTextActive]}>{t}</Text></Pressable>)}</View>; }
export function InfoRow({label,value,tone}){ const color=tone==="green"?P.color.green:tone==="red"?P.color.red:P.color.text; return <View style={s.infoRow}><Text style={s.infoLabel}>{label}</Text><Text style={[s.infoValue,{color}]}>{value}</Text></View>; }
export function ActivityRow({item}){ const buy=item.side==="BUY"; return <View style={s.activityRow}><View style={[s.activityIcon,{backgroundColor:buy?P.color.greenSoft:P.color.redSoft}]}><Text style={{color:buy?P.color.green:P.color.red,fontWeight:"900"}}>{buy?"B":"S"}</Text></View><View style={{flex:1}}><Text style={s.activityTitle}>{item.side} {item.symbol}</Text><Text style={s.activityMeta}>{item.status} · {item.brokerId}</Text></View><Text style={s.activityValue}>{item.qty} @ {item.price}</Text></View>; }
export function Disclaimer(){ return <View style={s.disclaimer}><Text style={s.disclaimerText}>AI-assisted decision support only. Confirm all trades through your selected licensed broker.</Text></View>; }
const s=StyleSheet.create({page:{flex:1,backgroundColor:P.color.bg},header:{paddingHorizontal:P.spacing.screen,paddingTop:18,paddingBottom:12,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{color:P.color.text,fontSize:24,fontWeight:"900"},subtitle:{color:P.color.muted,marginTop:3,fontSize:12},card:{backgroundColor:P.color.surface,borderRadius:P.radius.lg,borderWidth:1,borderColor:P.color.border,padding:P.spacing.card,marginHorizontal:P.spacing.screen,marginBottom:P.spacing.gap},cta:{minHeight:50,borderRadius:P.radius.md,borderWidth:1,alignItems:"center",justifyContent:"center",marginTop:10},ctaText:{color:P.color.white,fontWeight:"900",fontSize:15},segments:{flexDirection:"row",marginHorizontal:P.spacing.screen,marginBottom:12,padding:4,backgroundColor:P.color.surface,borderRadius:P.radius.md,borderWidth:1,borderColor:P.color.border},segment:{flex:1,minHeight:40,alignItems:"center",justifyContent:"center",borderRadius:P.radius.sm},segmentActive:{backgroundColor:P.color.blue},segmentText:{color:P.color.muted,fontWeight:"800",fontSize:12},segmentTextActive:{color:P.color.white},infoRow:{flexDirection:"row",justifyContent:"space-between",paddingVertical:9,borderBottomWidth:1,borderBottomColor:P.color.border},infoLabel:{color:P.color.muted},infoValue:{fontWeight:"900"},activityRow:{minHeight:64,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:P.color.border,paddingVertical:10},activityIcon:{width:38,height:38,borderRadius:12,alignItems:"center",justifyContent:"center"},activityTitle:{color:P.color.text,fontWeight:"900"},activityMeta:{color:P.color.muted,fontSize:11,marginTop:2},activityValue:{color:P.color.text,fontWeight:"800"},disclaimer:{marginHorizontal:P.spacing.screen,marginBottom:24,borderRadius:P.radius.lg,backgroundColor:P.color.blueSoft,borderWidth:1,borderColor:P.color.border,padding:12},disclaimerText:{color:P.color.text,fontSize:11,lineHeight:17}});
