export const EventTypes = {
  PORTFOLIO_CONCENTRATION: "PORTFOLIO_CONCENTRATION",
  SECTOR_CONCENTRATION: "SECTOR_CONCENTRATION",
  CASH_LOW: "CASH_LOW",
  CASH_HIGH: "CASH_HIGH",
  GOAL_PROGRESS: "GOAL_PROGRESS",
  DIVIDEND_DECLARED: "DIVIDEND_DECLARED",
  PRICE_ALERT: "PRICE_ALERT",
  BROKER_DISCONNECTED: "BROKER_DISCONNECTED",
  ORDER_FILLED: "ORDER_FILLED",
  ORDER_REJECTED: "ORDER_REJECTED"
};